const THRESHOLD = {
  HIGH_HP: 4,
  HIGH_ATK: 4,
  GENERAL_LOW_HP: 10,
  PLAY_CARD_HIGH_PRIORITY: 90,
  PLAY_CARD_MEDIUM_PRIORITY: 40,
  PLAY_CARD: 15,
  PLAY_CARD_MINIMUM: 7,
};

module.exports = THRESHOLD;
