FROM quay.io/marwanhilmi/duelyst-base:latest

RUN mkdir -p /app
WORKDIR /app

ADD package.json /app/
RUN npm install --production --loglevel warn
ADD . /app

# ENV VARS
ENV PORT 8080
ENV GAME_PORT 8080

# EXPOSE PORT
EXPOSE 8080

# remove folders/files that got copied over but we don't need

# remove build tools needed for native dependencies
RUN apk del make gcc g++ python git && \
  rm -rf /tmp/* /var/cache/apk/* /root/.npm /root/.node-gyp
