module.exports = {};

const NodeFactory = require('app/view/helpers/NodeFactory');

const BaseParticleSystem = require('app/view/nodes/BaseParticleSystem');
const BaseSprite = require('app/view/nodes/BaseSprite');
const BaseLabel = require('app/view/nodes/BaseLabel');
const FXSprite = require('app/view/nodes/fx/FXSprite');
const FXDistortionSprite = require('app/view/nodes/fx/FXDistortionSprite');
const FXProjectileSprite = require('app/view/nodes/fx/FXProjectileSprite');
const CausticPrismaticGlowSprite = require('app/view/nodes/fx/CausticPrismaticGlowSprite');
const FXBoidSprite = require('app/view/nodes/fx/FXBoidSprite');
const FXCardShineSprite = require('app/view/nodes/fx/FXCardShineSprite');
const FXCausticSprite = require('app/view/nodes/fx/FXCausticSprite');
const FXChainSprite = require('app/view/nodes/fx/FXChainSprite');
const FXChromaticFlareSprite = require('app/view/nodes/fx/FXChromaticFlareSprite');
const FXDecalSprite = require('app/view/nodes/fx/FXDecalSprite');
const FXDissolveWithDiscFromCenterSprite = require('app/view/nodes/fx/FXDissolveWithDiscFromCenterSprite');
const FXEnergyBallSprite = require('app/view/nodes/fx/FXEnergyBallSprite');
const FXEnergyBeamSprite = require('app/view/nodes/fx/FXEnergyBeamSprite');
const FXFbmNoiseGradientMaskedSprite = require('app/view/nodes/fx/FXFbmNoiseGradientMaskedSprite');
const FXFbmNoiseRaysSprite = require('app/view/nodes/fx/FXFbmNoiseRaysSprite');
const FXFbmPolarFlareSprite = require('app/view/nodes/fx/FXFbmPolarFlareSprite');
const FXFbmPolarFlareWipeSprite = require('app/view/nodes/fx/FXFbmPolarFlareWipeSprite');
const FXFireLinearWaveSprite = require('app/view/nodes/fx/FXFireLinearWaveSprite');
const FXFireRingFlareWarpedSprite = require('app/view/nodes/fx/FXFireRingFlareWarpedSprite');
const FXFireRingSprite = require('app/view/nodes/fx/FXFireRingSprite');
const FXFlockSprite = require('app/view/nodes/fx/FXFlockSprite');
const FXGlowImageMap = require('app/view/nodes/fx/FXGlowImageMap');
const FXHorizontalGlowFlareSprite = require('app/view/nodes/fx/FXHorizontalGlowFlareSprite');
const FXLensFlareSprite = require('app/view/nodes/fx/FXLensFlareSprite');
const FXRarityFlareSprite = require('app/view/nodes/fx/FXRarityFlareSprite');
const FXRipplingGlowImageMapSprite = require('app/view/nodes/fx/FXRipplingGlowImageMapSprite');
const FXShadowBlobSprite = require('app/view/nodes/fx/FXShadowBlobSprite');
const FXShockwaveSprite = require('app/view/nodes/fx/FXShockwaveSprite');
const FXTimerSprite = require('app/view/nodes/fx/FXTimerSprite');
const FXVortexSprite = require('app/view/nodes/fx/FXVortexSprite');
const FXWhiteCloudVignette = require('app/view/nodes/fx/FXWhiteCloudVignette');
const LensNoiseSprite = require('app/view/nodes/fx/LensNoiseSprite');
const Light = require('app/view/nodes/fx/Light');
const VoronoiPrismaticSprite = require('app/view/nodes/fx/VoronoiPrismaticSprite');

NodeFactory.setByType('Particles', BaseParticleSystem);
NodeFactory.setByType('Sprite', BaseSprite);
NodeFactory.setByType('Label', BaseLabel);
NodeFactory.setByType('CausticPrismaticGlow', CausticPrismaticGlowSprite);
NodeFactory.setByType('Boid', FXBoidSprite);
NodeFactory.setByType('CardShine', FXCardShineSprite);
NodeFactory.setByType('Caustic', FXCausticSprite);
NodeFactory.setByType('Chain', FXChainSprite);
NodeFactory.setByType('ChromaticFlare', FXChromaticFlareSprite);
NodeFactory.setByType('Decal', FXDecalSprite);
NodeFactory.setByType('DissolveWithDiscFromCenterSprite', FXDissolveWithDiscFromCenterSprite);
NodeFactory.setByType('Distortion', FXDistortionSprite);
NodeFactory.setByType('EnergyBall', FXEnergyBallSprite);
NodeFactory.setByType('EnergyBeam', FXEnergyBeamSprite);
NodeFactory.setByType('FbmNoiseGradientMaskedSprite', FXFbmNoiseGradientMaskedSprite);
NodeFactory.setByType('FbmNoiseRaysSprite', FXFbmNoiseRaysSprite);
NodeFactory.setByType('FbmPolarFlareSprite', FXFbmPolarFlareSprite);
NodeFactory.setByType('FbmPolarFlareWipeSprite', FXFbmPolarFlareWipeSprite);
NodeFactory.setByType('FireLinearWave', FXFireLinearWaveSprite);
NodeFactory.setByType('FireRingFlareWarped', FXFireRingFlareWarpedSprite);
NodeFactory.setByType('FireRing', FXFireRingSprite);
NodeFactory.setByType('Flocking', FXFlockSprite);
NodeFactory.setByType('GlowImageMap', FXGlowImageMap);
NodeFactory.setByType('HorizontalGlowFlareSprite', FXHorizontalGlowFlareSprite);
NodeFactory.setByType('LensFlare', FXLensFlareSprite);
NodeFactory.setByType('Projectile', FXProjectileSprite);
NodeFactory.setByType('RarityFlareSprite', FXRarityFlareSprite);
NodeFactory.setByType('FXRipplingGlowImageMapSprite', FXRipplingGlowImageMapSprite);
NodeFactory.setByType('ShadowBlob', FXShadowBlobSprite);
NodeFactory.setByType('Shockwave', FXShockwaveSprite);
NodeFactory.setByType('FXSprite', FXSprite);
NodeFactory.setByType('Timer', FXTimerSprite);
NodeFactory.setByType('Vortex', FXVortexSprite);
NodeFactory.setByType('WhiteCloudVignette', FXWhiteCloudVignette);
NodeFactory.setByType('LensNoiseSprite', LensNoiseSprite);
NodeFactory.setByType('Light', Light);
NodeFactory.setByType('VoronoiPrismatic', VoronoiPrismaticSprite);
