module.exports = {};

var NodeFactory = require("app/view/helpers/NodeFactory");

var BaseParticleSystem = require('app/view/nodes/BaseParticleSystem');
var BaseSprite = require('app/view/nodes/BaseSprite');
var BaseLabel = require('app/view/nodes/BaseLabel');
var FXSprite = require('app/view/nodes/fx/FXSprite');
var FXDistortionSprite = require('app/view/nodes/fx/FXDistortionSprite');
var FXProjectileSprite = require('app/view/nodes/fx/FXProjectileSprite');
var CausticPrismaticGlowSprite = require('app/view/nodes/fx/CausticPrismaticGlowSprite');
var FXBoidSprite = require('app/view/nodes/fx/FXBoidSprite');
var FXCardShineSprite = require('app/view/nodes/fx/FXCardShineSprite');
var FXCausticSprite = require('app/view/nodes/fx/FXCausticSprite');
var FXChainSprite = require('app/view/nodes/fx/FXChainSprite');
var FXChromaticFlareSprite = require('app/view/nodes/fx/FXChromaticFlareSprite');
var FXDecalSprite = require('app/view/nodes/fx/FXDecalSprite');
var FXDissolveWithDiscFromCenterSprite = require('app/view/nodes/fx/FXDissolveWithDiscFromCenterSprite');
var FXEnergyBallSprite = require('app/view/nodes/fx/FXEnergyBallSprite');
var FXEnergyBeamSprite = require('app/view/nodes/fx/FXEnergyBeamSprite');
var FXFbmNoiseGradientMaskedSprite = require('app/view/nodes/fx/FXFbmNoiseGradientMaskedSprite');
var FXFbmNoiseRaysSprite = require('app/view/nodes/fx/FXFbmNoiseRaysSprite');
var FXFbmPolarFlareSprite = require('app/view/nodes/fx/FXFbmPolarFlareSprite');
var FXFbmPolarFlareWipeSprite = require('app/view/nodes/fx/FXFbmPolarFlareWipeSprite');
var FXFireLinearWaveSprite = require('app/view/nodes/fx/FXFireLinearWaveSprite');
var FXFireRingFlareWarpedSprite = require('app/view/nodes/fx/FXFireRingFlareWarpedSprite');
var FXFireRingSprite = require('app/view/nodes/fx/FXFireRingSprite');
var FXFlockSprite = require('app/view/nodes/fx/FXFlockSprite');
var FXGlowImageMap = require('app/view/nodes/fx/FXGlowImageMap');
var FXHorizontalGlowFlareSprite = require('app/view/nodes/fx/FXHorizontalGlowFlareSprite');
var FXLensFlareSprite = require('app/view/nodes/fx/FXLensFlareSprite');
var FXRarityFlareSprite = require('app/view/nodes/fx/FXRarityFlareSprite');
var FXRipplingGlowImageMapSprite = require('app/view/nodes/fx/FXRipplingGlowImageMapSprite');
var FXShadowBlobSprite = require('app/view/nodes/fx/FXShadowBlobSprite');
var FXShockwaveSprite = require('app/view/nodes/fx/FXShockwaveSprite');
var FXTimerSprite = require('app/view/nodes/fx/FXTimerSprite');
var FXVortexSprite = require('app/view/nodes/fx/FXVortexSprite');
var FXWhiteCloudVignette = require('app/view/nodes/fx/FXWhiteCloudVignette');
var LensNoiseSprite = require('app/view/nodes/fx/LensNoiseSprite');
var Light = require('app/view/nodes/fx/Light');
var VoronoiPrismaticSprite = require('app/view/nodes/fx/VoronoiPrismaticSprite');

NodeFactory.setByType("Particles", BaseParticleSystem);
NodeFactory.setByType("Sprite", BaseSprite);
NodeFactory.setByType("Label", BaseLabel);
NodeFactory.setByType("CausticPrismaticGlow", CausticPrismaticGlowSprite);
NodeFactory.setByType("Boid", FXBoidSprite);
NodeFactory.setByType("CardShine", FXCardShineSprite);
NodeFactory.setByType("Caustic", FXCausticSprite);
NodeFactory.setByType("Chain", FXChainSprite);
NodeFactory.setByType("ChromaticFlare", FXChromaticFlareSprite);
NodeFactory.setByType("Decal", FXDecalSprite);
NodeFactory.setByType("DissolveWithDiscFromCenterSprite", FXDissolveWithDiscFromCenterSprite);
NodeFactory.setByType("Distortion", FXDistortionSprite);
NodeFactory.setByType("EnergyBall", FXEnergyBallSprite);
NodeFactory.setByType("EnergyBeam", FXEnergyBeamSprite);
NodeFactory.setByType("FbmNoiseGradientMaskedSprite", FXFbmNoiseGradientMaskedSprite);
NodeFactory.setByType("FbmNoiseRaysSprite", FXFbmNoiseRaysSprite);
NodeFactory.setByType("FbmPolarFlareSprite", FXFbmPolarFlareSprite);
NodeFactory.setByType("FbmPolarFlareWipeSprite", FXFbmPolarFlareWipeSprite);
NodeFactory.setByType("FireLinearWave", FXFireLinearWaveSprite);
NodeFactory.setByType("FireRingFlareWarped", FXFireRingFlareWarpedSprite);
NodeFactory.setByType("FireRing", FXFireRingSprite);
NodeFactory.setByType("Flocking", FXFlockSprite);
NodeFactory.setByType("GlowImageMap", FXGlowImageMap);
NodeFactory.setByType("HorizontalGlowFlareSprite", FXHorizontalGlowFlareSprite);
NodeFactory.setByType("LensFlare", FXLensFlareSprite);
NodeFactory.setByType("Projectile", FXProjectileSprite);
NodeFactory.setByType("RarityFlareSprite", FXRarityFlareSprite);
NodeFactory.setByType("FXRipplingGlowImageMapSprite", FXRipplingGlowImageMapSprite);
NodeFactory.setByType("ShadowBlob", FXShadowBlobSprite);
NodeFactory.setByType("Shockwave", FXShockwaveSprite);
NodeFactory.setByType("FXSprite", FXSprite);
NodeFactory.setByType("Timer", FXTimerSprite);
NodeFactory.setByType("Vortex", FXVortexSprite);
NodeFactory.setByType("WhiteCloudVignette", FXWhiteCloudVignette);
NodeFactory.setByType("LensNoiseSprite", LensNoiseSprite);
NodeFactory.setByType("Light", Light);
NodeFactory.setByType("VoronoiPrismatic", VoronoiPrismaticSprite);
